### ISSUE TITLE
安装的时出现UnicodeError

### ISSUE THREAD

**Issue by ilumer** [lxyu/weibo#12]
Traceback (most recent call last):
    File "<string>", line 20, in <module>
    File "C:\Users\qiao\AppData\Local\Temp\pip-build-2wl7dm3o\weibo\setup.py", line 15, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 241: illegal multibyte sequence

```
----------------------------------------
```

   Command "python setup.py egg_info" failed with error code 1 in  
   C:\Users\qiao\AppData\Local\Temp\pip-build-2wl7dm3o\weibo
 windows10+python3.4

**Comment by lxyu** [comment]
Try to change your shell encode to UTF-8.

**Comment by lojp** [comment]
Is it possible to add this 'encoding="utf-8"' into setup.py file? like this
long_description=open('README.rst',encoding='utf-8').read().
