### ISSUE TITLE
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by y500** [lxyu/weibo#13]
> > > c.get('users/show', uid=1282440983)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/weibo.py", line 107, in get
> > >     self._assert_error(res)
> > >   File "/usr/lib/python2.7/site-packages/weibo.py", line 95, in _assert_error
> > >     d.get("error_code", ""), d.get("error", "")))
> > > RuntimeError: 21333 forbid use this authentication type: basic

**Comment by lxyu** [comment]
问题无法重现。请给出更多信息或可重现脚本。

我猜测是和你的本地环境有关，或者加入了"中间人"代理导致 ssl 验证失败。如果要强制通过，参考 requests lib 里面的禁用 ssl 验证的方法。
