### ISSUE TITLE
如何不用通过浏览器请求获取到code

### ISSUE THREAD

**Issue by hillerliao** [lxyu/weibo#15]
如何不用通过浏览器请求获取到code，就像官方的sdk那样，最好能实现这个。

**Comment by iewaij** [comment]
使用账号认证方式即可跳过 code 获取。

    >>> from weibo import Client
    >>> c = Client(API_KEY, API_SECRET, REDIRECT_URI, username='admin', password='secret')
    >>> c.get('users/show', uid=1282440983)
