### ISSUE TITLE
what is rediract_uri send?

### ISSUE THREAD

**Issue by lucasjinreal** [lxyu/weibo#16]
So how do pass redirect_uri argument exactly? any example?

**Comment by theandychung** [comment]
@jinfagang remember where you get the app key and app secret in "基本信息" tab? Go to the next tab "高級信息" and add a website address at "OAuth2.0 授权设置">"授权回调页" and "取消授权回调页". If you don't have anything in mind just set it to the default most people use: http://api.weibo.com/oauth2/default.html

![](https://i.imgur.com/iuSzBqN.png)
