### ISSUE TITLE
hey，表扬一下

### ISSUE THREAD

**Issue by MOON-CLJ** [lxyu/weibo#2]
你写的这个很不错，我有一个小项目一直在用，你应该对微博比较感兴趣，我的项目地址是http://idec.buaa.edu.cn:8080/ 你可以看一下，如果有兴趣可以加入开发哦

**Comment by lxyu** [comment]
我只是对一个人的微博有兴趣，对 weibo 没有兴趣。所以项目就不参与了。

这个 sdk 主要是给自己的一个爬虫脚本用的。也放在这里了 [Weibo Spy](http://lxyu.github.com/weibo_spy/)，有兴趣的话可以参考下。 : )
