### ISSUE TITLE
报错 TypeError: session() takes no arguments (1 given)

### ISSUE THREAD

**Issue by bgee** [lxyu/weibo#4]
### Requests版本1.0.4

File "bot.py", line 9, in <module>
    c.set_code(code)
  File "/Library/Python/2.7/site-packages/weibo.py", line 83, in set_code
    self.set_token(tk['access_token'], time.time() + int(tk['expires_in']))
  File "/Library/Python/2.7/site-packages/weibo.py", line 92, in set_token
    params={'access_token': self.access_token})
TypeError: session() takes no arguments (1 given)

**Comment by lxyu** [comment]
我这里无法重现，请按照 http://lxyu.github.com/weibo/ 这里的过程重试一下看看是否还有问题。

**Comment by CNBorn** [comment]
将92行改为

```
self.session = requests.session()
self.session.params={'access_token': self.access_token}
```

**Comment by lxyu** [comment]
Thanks.
