### ISSUE TITLE
是否支持新浪的几个特殊部署的接口？

### ISSUE THREAD

**Issue by biergaizi** [lxyu/weibo#5]
`remind/unread_count` 这个接口的域名是 `https://rm.api.weibo.com`，类似的情况不只是这一个接口，不知本 SDK 能否正常工作？

**Comment by lxyu** [comment]
看了下，确实忽略掉了。真心没有想到新浪能奇葩如此。

大致看了一下，应该是下面这3个接口:
1. `remind/unread_count`, http://open.weibo.com/wiki/2/remind/unread_count
2. `remind/set_count`, http://open.weibo.com/wiki/2/remind/set_count
3. `statuses/upload`, http://open.weibo.com/wiki/2/statuses/upload

不知道是否有补充？

要支持这几个接口很简单，我这周末找时间测试下。

**Comment by biergaizi** [comment]
其它的特殊接口暂时没有发现，谢谢了。
不过如果对这些接口特殊处理，估计会出现一堆的 `if` 判断，恐怕代码要乱一些了，不知你有什么技巧能让代码看上去干净一些，我也学习学习。

**Comment by biergaizi** [comment]
另外不知此 SDK 是否支持图片 Post 上传？

**Comment by lxyu** [comment]
你指的是 `statuses/upload` 接口吧，其实上传图片也是 HTTP POST，当然是可以支持的。

**Comment by slawdan** [comment]
`api.weibo.com`兼容`statuses/upload`接口，可以直接使用，但需要对post做修改，我已经提交pull request :D

remind的域名`rm.api.weibo.com`似乎也是能够被`api.weibo.com` 兼容的：
`$ curl "https://rm.api.weibo.com/2/remind/set_count.json"`
`{"error":"auth faild!","error_code":21301,"request":"/2/remind/set_count.json"}`

如果是不存在的接口，错误提示是：
`{"error":"Request Api not found!","error_code":10020,"request":"/2/remind/set_count2.json"}`

**Comment by lxyu** [comment]
经测试，remind 接口兼容。已添加 upload 支持。
